INSERT INTO CROP_CATEGORY(id,name) VALUES (1,'Fruits');
INSERT INTO CROP_CATEGORY(id,name) VALUES (2,'Vegetables');
INSERT INTO CROP_CATEGORY(id,name) VALUES (3,'Grains');
INSERT INTO CROP_CATEGORY(id,name) VALUES (4,'Pulses');
INSERT INTO CROP_CATEGORY(id,name) VALUES (5,'Spices');
INSERT INTO CROP_CATEGORY(id,name) VALUES (6,'Flowers');
INSERT INTO CROP_CATEGORY(id,name) VALUES (7,'Hurbs');