INSERT INTO city(id,name,state_name) VALUES ('1','Mumbai','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('2','Delhi','Delhi');
INSERT INTO city(id,name,state_name) VALUES ('3','Bengaluru','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('4','Ahmedabad','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('5','Hyderabad','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('6','Chennai','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('7','Kolkata','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('8','Pune','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('9','Jaipur','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('10','Surat','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('11','Lucknow','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('12','Kanpur','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('13','Nagpur','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('14','Patna','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('15','Indore','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('16','Thane','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('17','Bhopal','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('18','Visakhapatnam','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('19','Vadodara','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('20','Firozabad','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('21','Ludhiana','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('22','Rajkot','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('23','Agra','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('24','Siliguri','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('25','Nashik','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('26','Faridabad','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('27','Patiala','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('28','Meerut','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('29','Kalyan-Dombivali','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('30','Vasai-Virar','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('31','Varanasi','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('32','Srinagar','Jammu and Kashmir');
INSERT INTO city(id,name,state_name) VALUES ('33','Dhanbad','Jharkhand');
INSERT INTO city(id,name,state_name) VALUES ('34','Jodhpur','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('35','Amritsar','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('36','Raipur','Chhattisgarh');
INSERT INTO city(id,name,state_name) VALUES ('37','Allahabad','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('38','Coimbatore','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('39','Jabalpur','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('40','Gwalior','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('41','Vijayawada','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('42','Madurai','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('43','Guwahati','Assam');
INSERT INTO city(id,name,state_name) VALUES ('44','Chandigarh','Chandigarh');
INSERT INTO city(id,name,state_name) VALUES ('45','Hubli-Dharwad','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('46','Amroha','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('47','Moradabad','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('48','Gurgaon','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('49','Aligarh','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('50','Solapur','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('51','Ranchi','Jharkhand');
INSERT INTO city(id,name,state_name) VALUES ('52','Jalandhar','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('53','Tiruchirappalli','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('54','Bhubaneswar','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('55','Salem','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('56','Warangal','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('57','Mira-Bhayandar','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('58','Thiruvananthapuram','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('59','Bhiwandi','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('60','Saharanpur','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('61','Guntur','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('62','Amravati','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('63','Bikaner','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('64','Noida','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('65','Jamshedpur','Jharkhand');
INSERT INTO city(id,name,state_name) VALUES ('66','Bhilai Nagar','Chhattisgarh');
INSERT INTO city(id,name,state_name) VALUES ('67','Cuttack','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('68','Kochi','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('69','Udaipur','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('70','Bhavnagar','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('71','Dehradun','Uttarakhand');
INSERT INTO city(id,name,state_name) VALUES ('72','Asansol','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('73','Nanded-Waghala','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('74','Ajmer','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('75','Jamnagar','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('76','Ujjain','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('77','Sangli','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('78','Loni','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('79','Jhansi','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('80','Pondicherry','Puducherry');
INSERT INTO city(id,name,state_name) VALUES ('81','Nellore','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('82','Jammu','Jammu and Kashmir');
INSERT INTO city(id,name,state_name) VALUES ('83','Belagavi','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('84','Raurkela','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('85','Mangaluru','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('86','Tirunelveli','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('87','Malegaon','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('88','Gaya','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('89','Tiruppur','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('90','Davanagere','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('91','Kozhikode','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('92','Akola','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('93','Kurnool','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('94','Bokaro Steel City','Jharkhand');
INSERT INTO city(id,name,state_name) VALUES ('95','Rajahmundry','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('96','Ballari','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('97','Agartala','Tripura');
INSERT INTO city(id,name,state_name) VALUES ('98','Bhagalpur','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('99','Latur','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('100','Dhule','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('101','Korba','Chhattisgarh');
INSERT INTO city(id,name,state_name) VALUES ('102','Bhilwara','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('103','Brahmapur','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('104','Mysore','Karnatka');
INSERT INTO city(id,name,state_name) VALUES ('105','Muzaffarpur','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('106','Ahmednagar','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('107','Kollam','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('108','Raghunathganj','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('109','Bilaspur','Chhattisgarh');
INSERT INTO city(id,name,state_name) VALUES ('110','Shahjahanpur','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('111','Thrissur','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('112','Alwar','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('113','Kakinada','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('114','Nizamabad','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('115','Sagar','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('116','Tumkur','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('117','Hisar','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('118','Rohtak','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('119','Panipat','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('120','Darbhanga','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('121','Kharagpur','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('122','Aizawl','Mizoram');
INSERT INTO city(id,name,state_name) VALUES ('123','Ichalkaranji','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('124','Tirupati','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('125','Karnal','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('126','Bathinda','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('127','Rampur','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('128','Shivamogga','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('129','Ratlam','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('130','Modinagar','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('131','Durg','Chhattisgarh');
INSERT INTO city(id,name,state_name) VALUES ('132','Shillong','Meghalaya');
INSERT INTO city(id,name,state_name) VALUES ('133','Imphal','Manipur');
INSERT INTO city(id,name,state_name) VALUES ('134','Hapur','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('135','Ranipet','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('136','Anantapur','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('137','Arrah','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('138','Karimnagar','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('139','Parbhani','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('140','Etawah','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('141','Bharatpur','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('142','Begusarai','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('143','New Delhi','Delhi');
INSERT INTO city(id,name,state_name) VALUES ('144','Chhapra','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('145','Kadapa','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('146','Ramagundam','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('147','Pali','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('148','Satna','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('149','Vizianagaram','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('150','Katihar','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('151','Hardwar','Uttarakhand');
INSERT INTO city(id,name,state_name) VALUES ('152','Sonipat','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('153','Nagercoil','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('154','Thanjavur','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('155','Murwara (Katni)','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('156','Naihati','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('157','Sambhal','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('158','Nadiad','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('159','Yamunanagar','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('160','English Bazar','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('161','Eluru','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('162','Munger','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('163','Panchkula','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('164','Raayachuru','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('165','Panvel','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('166','Deoghar','Jharkhand');
INSERT INTO city(id,name,state_name) VALUES ('167','Ongole','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('168','Nandyal','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('169','Morena','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('170','Bhiwani','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('171','Porbandar','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('172','Palakkad','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('173','Anand','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('174','Purnia','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('175','Baharampur','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('176','Barmer','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('177','Morvi','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('178','Orai','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('179','Bahraich','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('180','Sikar','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('181','Vellore','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('182','Singrauli','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('183','Khammam','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('184','Mahesana','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('185','Silchar','Assam');
INSERT INTO city(id,name,state_name) VALUES ('186','Sambalpur','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('187','Rewa','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('188','Unnao','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('189','Hugli-Chinsurah','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('190','Raiganj','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('191','Phusro','Jharkhand');
INSERT INTO city(id,name,state_name) VALUES ('192','Adityapur','Jharkhand');
INSERT INTO city(id,name,state_name) VALUES ('193','Alappuzha','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('194','Bahadurgarh','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('195','Machilipatnam','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('196','Rae Bareli','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('197','Jalpaiguri','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('198','Bharuch','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('199','Pathankot','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('200','Hoshiarpur','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('201','Baramula','Jammu and Kashmir');
INSERT INTO city(id,name,state_name) VALUES ('202','Adoni','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('203','Jind','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('204','Tonk','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('205','Tenali','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('206','Kancheepuram','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('207','Vapi','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('208','Sirsa','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('209','Navsari','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('210','Mahbubnagar','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('211','Puri','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('212','Robertson Pet','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('213','Erode','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('214','Batala','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('215','Haldwani-cum-Kathgodam','Uttarakhand');
INSERT INTO city(id,name,state_name) VALUES ('216','Vidisha','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('217','Saharsa','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('218','Thanesar','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('219','Chittoor','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('220','Veraval','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('221','Lakhimpur','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('222','Sitapur','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('223','Hindupur','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('224','Santipur','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('225','Balurghat','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('226','Ganjbasoda','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('227','Moga','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('228','Proddatur','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('229','Srinagar','Uttarakhand');
INSERT INTO city(id,name,state_name) VALUES ('230','Medinipur','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('231','Habra','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('232','Sasaram','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('233','Hajipur','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('234','Bhuj','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('235','Shivpuri','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('236','Ranaghat','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('237','Shimla','Himachal Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('238','Tiruvannamalai','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('239','Kaithal','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('240','Rajnandgaon','Chhattisgarh');
INSERT INTO city(id,name,state_name) VALUES ('241','Godhra','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('242','Hazaribag','Jharkhand');
INSERT INTO city(id,name,state_name) VALUES ('243','Bhimavaram','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('244','Mandsaur','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('245','Dibrugarh','Assam');
INSERT INTO city(id,name,state_name) VALUES ('246','Kolar','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('247','Bankura','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('248','Mandya','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('249','Dehri-on-Sone','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('250','Madanapalle','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('251','Malerkotla','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('252','Lalitpur','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('253','Bettiah','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('254','Pollachi','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('255','Khanna','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('256','Neemuch','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('257','Palwal','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('258','Palanpur','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('259','Guntakal','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('260','Nabadwip','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('261','Udupi','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('262','Jagdalpur','Chhattisgarh');
INSERT INTO city(id,name,state_name) VALUES ('263','Motihari','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('264','Pilibhit','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('265','Dimapur','Nagaland');
INSERT INTO city(id,name,state_name) VALUES ('266','Mohali','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('267','Sadulpur','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('268','Rajapalayam','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('269','Dharmavaram','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('270','Kashipur','Uttarakhand');
INSERT INTO city(id,name,state_name) VALUES ('271','Sivakasi','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('272','Darjiling','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('273','Chikkamagaluru','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('274','Gudivada','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('275','Baleshwar Town','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('276','Mancherial','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('277','Srikakulam','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('278','Adilabad','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('279','Yavatmal','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('280','Barnala','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('281','Nagaon','Assam');
INSERT INTO city(id,name,state_name) VALUES ('282','Narasaraopet','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('283','Raigarh','Chhattisgarh');
INSERT INTO city(id,name,state_name) VALUES ('284','Roorkee','Uttarakhand');
INSERT INTO city(id,name,state_name) VALUES ('285','Valsad','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('286','Ambikapur','Chhattisgarh');
INSERT INTO city(id,name,state_name) VALUES ('287','Giridih','Jharkhand');
INSERT INTO city(id,name,state_name) VALUES ('288','Chandausi','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('289','Purulia','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('290','Patan','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('291','Bagaha','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('292','Hardoi','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('293','Achalpur','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('294','Osmanabad','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('295','Deesa','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('296','Nandurbar','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('297','Azamgarh','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('298','Ramgarh','Jharkhand');
INSERT INTO city(id,name,state_name) VALUES ('299','Firozpur','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('300','Baripada Town','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('301','Karwar','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('302','Siwan','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('303','Rajampet','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('304','Pudukkottai','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('305','Anantnag','Jammu and Kashmir');
INSERT INTO city(id,name,state_name) VALUES ('306','Tadpatri','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('307','Satara','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('308','Bhadrak','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('309','Kishanganj','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('310','Suryapet','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('311','Wardha','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('312','Ranebennuru','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('313','Amreli','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('314','Neyveli (TS)','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('315','Jamalpur','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('316','Marmagao','Goa');
INSERT INTO city(id,name,state_name) VALUES ('317','Udgir','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('318','Tadepalligudem','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('319','Nagapattinam','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('320','Buxar','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('321','Aurangabad','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('322','Jehanabad','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('323','Phagwara','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('324','Khair','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('325','Sawai Madhopur','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('326','Kapurthala','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('327','Chilakaluripet','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('328','Aurangabad','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('329','Malappuram','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('330','Rewari','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('331','Nagaur','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('332','Sultanpur','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('333','Nagda','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('334','Port Blair','Andaman and Nicobar Islands');
INSERT INTO city(id,name,state_name) VALUES ('335','Lakhisarai','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('336','Panaji','Goa');
INSERT INTO city(id,name,state_name) VALUES ('337','Tinsukia','Assam');
INSERT INTO city(id,name,state_name) VALUES ('338','Itarsi','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('339','Kohima','Nagaland');
INSERT INTO city(id,name,state_name) VALUES ('340','Balangir','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('341','Nawada','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('342','Jharsuguda','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('343','Jagtial','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('344','Viluppuram','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('345','Amalner','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('346','Zirakpur','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('347','Tanda','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('348','Tiruchengode','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('349','Nagina','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('350','Yemmiganur','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('351','Vaniyambadi','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('352','Sarni','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('353','Theni Allinagaram','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('354','Margao','Goa');
INSERT INTO city(id,name,state_name) VALUES ('355','Akot','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('356','Sehore','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('357','Mhow Cantonment','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('358','Kot Kapura','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('359','Makrana','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('360','Pandharpur','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('361','Miryalaguda','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('362','Shamli','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('363','Seoni','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('364','Ranibennur','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('365','Kadiri','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('366','Shrirampur','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('367','Rudrapur','Uttarakhand');
INSERT INTO city(id,name,state_name) VALUES ('368','Parli','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('369','Najibabad','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('370','Nirmal','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('371','Udhagamandalam','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('372','Shikohabad','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('373','Jhumri Tilaiya','Jharkhand');
INSERT INTO city(id,name,state_name) VALUES ('374','Aruppukkottai','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('375','Ponnani','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('376','Jamui','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('377','Sitamarhi','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('378','Chirala','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('379','Anjar','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('380','Karaikal','Puducherry');
INSERT INTO city(id,name,state_name) VALUES ('381','Hansi','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('382','Anakapalle','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('383','Mahasamund','Chhattisgarh');
INSERT INTO city(id,name,state_name) VALUES ('384','Faridkot','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('385','Saunda','Jharkhand');
INSERT INTO city(id,name,state_name) VALUES ('386','Dhoraji','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('387','Paramakudi','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('388','Balaghat','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('389','Sujangarh','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('390','Khambhat','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('391','Muktsar','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('392','Rajpura','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('393','Kavali','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('394','Dhamtari','Chhattisgarh');
INSERT INTO city(id,name,state_name) VALUES ('395','Ashok Nagar','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('396','Sardarshahar','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('397','Mahuva','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('398','Bargarh','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('399','Kamareddy','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('400','Sahibganj','Jharkhand');
INSERT INTO city(id,name,state_name) VALUES ('401','Kothagudem','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('402','Ramanagaram','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('403','Gokak','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('404','Tikamgarh','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('405','Araria','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('406','Rishikesh','Uttarakhand');
INSERT INTO city(id,name,state_name) VALUES ('407','Shahdol','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('408','Medininagar (Daltonganj)','Jharkhand');
INSERT INTO city(id,name,state_name) VALUES ('409','Arakkonam','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('410','Washim','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('411','Sangrur','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('412','Bodhan','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('413','Fazilka','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('414','Palacole','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('415','Keshod','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('416','Sullurpeta','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('417','Wadhwan','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('418','Gurdaspur','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('419','Vatakara','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('420','Tura','Meghalaya');
INSERT INTO city(id,name,state_name) VALUES ('421','Narnaul','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('422','Kharar','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('423','Yadgir','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('424','Ambejogai','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('425','Ankleshwar','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('426','Savarkundla','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('427','Paradip','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('428','Virudhachalam','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('429','Kanhangad','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('430','Kadi','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('431','Srivilliputhur','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('432','Gobindgarh','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('433','Tindivanam','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('434','Mansa','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('435','Taliparamba','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('436','Manmad','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('437','Tanuku','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('438','Rayachoti','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('439','Virudhunagar','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('440','Koyilandy','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('441','Jorhat','Assam');
INSERT INTO city(id,name,state_name) VALUES ('442','Karur','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('443','Valparai','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('444','Srikalahasti','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('445','Neyyattinkara','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('446','Bapatla','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('447','Fatehabad','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('448','Malout','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('449','Sankarankovil','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('450','Tenkasi','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('451','Ratnagiri','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('452','Rabkavi Banhatti','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('453','Sikandrabad','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('454','Chaibasa','Jharkhand');
INSERT INTO city(id,name,state_name) VALUES ('455','Chirmiri','Chhattisgarh');
INSERT INTO city(id,name,state_name) VALUES ('456','Palwancha','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('457','Bhawanipatna','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('458','Kayamkulam','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('459','Pithampur','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('460','Nabha','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('461','Shahabad, Hardoi','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('462','Dhenkanal','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('463','Uran Islampur','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('464','Gopalganj','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('465','Bongaigaon City','Assam');
INSERT INTO city(id,name,state_name) VALUES ('466','Palani','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('467','Pusad','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('468','Sopore','Jammu and Kashmir');
INSERT INTO city(id,name,state_name) VALUES ('469','Pilkhuwa','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('470','Tarn Taran','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('471','Renukoot','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('472','Mandamarri','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('473','Shahabad','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('474','Barbil','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('475','Koratla','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('476','Madhubani','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('477','Arambagh','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('478','Gohana','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('479','Ladnu','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('480','Pattukkottai','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('481','Sirsi','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('482','Sircilla','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('483','Tamluk','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('484','Jagraon','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('485','AlipurdUrban Agglomerationr','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('486','Alirajpur','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('487','Tandur','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('488','Naidupet','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('489','Tirupathur','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('490','Tohana','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('491','Ratangarh','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('492','Dhubri','Assam');
INSERT INTO city(id,name,state_name) VALUES ('493','Masaurhi','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('494','Visnagar','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('495','Vrindavan','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('496','Nokha','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('497','Nagari','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('498','Narwana','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('499','Ramanathapuram','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('500','Ujhani','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('501','Samastipur','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('502','Laharpur','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('503','Sangamner','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('504','Nimbahera','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('505','Siddipet','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('506','Suri','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('507','Diphu','Assam');
INSERT INTO city(id,name,state_name) VALUES ('508','Jhargram','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('509','Shirpur-Warwade','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('510','Tilhar','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('511','Sindhnur','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('512','Udumalaipettai','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('513','Malkapur','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('514','Wanaparthy','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('515','Gudur','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('516','Kendujhar','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('517','Mandla','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('518','Mandi','Himachal Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('519','Nedumangad','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('520','North Lakhimpur','Assam');
INSERT INTO city(id,name,state_name) VALUES ('521','Vinukonda','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('522','Tiptur','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('523','Gobichettipalayam','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('524','Sunabeda','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('525','Wani','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('526','Upleta','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('527','Narasapuram','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('528','Nuzvid','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('529','Tezpur','Assam');
INSERT INTO city(id,name,state_name) VALUES ('530','Una','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('531','Markapur','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('532','Sheopur','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('533','Thiruvarur','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('534','Sidhpur','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('535','Sahaswan','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('536','Suratgarh','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('537','Shajapur','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('538','Rayagada','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('539','Lonavla','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('540','Ponnur','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('541','Kagaznagar','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('542','Gadwal','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('543','Bhatapara','Chhattisgarh');
INSERT INTO city(id,name,state_name) VALUES ('544','Kandukur','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('545','Sangareddy','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('546','Unjha','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('547','Lunglei','Mizoram');
INSERT INTO city(id,name,state_name) VALUES ('548','Karimganj','Assam');
INSERT INTO city(id,name,state_name) VALUES ('549','Kannur','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('550','Bobbili','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('551','Mokameh','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('552','Talegaon Dabhade','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('553','Anjangaon','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('554','Mangrol','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('555','Sunam','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('556','Gangarampur','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('557','Thiruvallur','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('558','Tirur','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('559','Rath','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('560','Jatani','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('561','Viramgam','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('562','Rajsamand','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('563','Yanam','Puducherry');
INSERT INTO city(id,name,state_name) VALUES ('564','Kottayam','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('565','Panruti','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('566','Dhuri','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('567','Namakkal','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('568','Kasaragod','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('569','Modasa','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('570','Rayadurg','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('571','Supaul','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('572','Kunnamkulam','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('573','Umred','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('574','Bellampalle','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('575','Sibsagar','Assam');
INSERT INTO city(id,name,state_name) VALUES ('576','Mandi Dabwali','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('577','Ottappalam','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('578','Dumraon','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('579','Samalkot','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('580','Jaggaiahpet','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('581','Goalpara','Assam');
INSERT INTO city(id,name,state_name) VALUES ('582','Tuni','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('583','Lachhmangarh','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('584','Bhongir','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('585','Amalapuram','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('586','Firozpur Cantt.','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('587','Vikarabad','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('588','Thiruvalla','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('589','Sherkot','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('590','Palghar','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('591','Shegaon','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('592','Jangaon','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('593','Bheemunipatnam','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('594','Panna','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('595','Thodupuzha','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('596','KathUrban Agglomeration','Jammu and Kashmir');
INSERT INTO city(id,name,state_name) VALUES ('597','Palitana','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('598','Arwal','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('599','Venkatagiri','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('600','Kalpi','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('601','Rajgarh (Churu)','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('602','Sattenapalle','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('603','Arsikere','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('604','Ozar','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('605','Thirumangalam','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('606','Petlad','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('607','Nasirabad','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('608','Phaltan','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('609','Rampurhat','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('610','Nanjangud','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('611','Forbesganj','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('612','Tundla','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('613','BhabUrban Agglomeration','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('614','Sagara','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('615','Pithapuram','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('616','Sira','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('617','Bhadrachalam','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('618','Charkhi Dadri','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('619','Chatra','Jharkhand');
INSERT INTO city(id,name,state_name) VALUES ('620','Palasa Kasibugga','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('621','Nohar','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('622','Yevla','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('623','Sirhind Fatehgarh Sahib','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('624','Bhainsa','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('625','Parvathipuram','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('626','Shahade','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('627','Chalakudy','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('628','Narkatiaganj','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('629','Kapadvanj','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('630','Macherla','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('631','Raghogarh-Vijaypur','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('632','Rupnagar','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('633','Naugachhia','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('634','Sendhwa','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('635','Byasanagar','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('636','Sandila','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('637','Gooty','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('638','Salur','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('639','Nanpara','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('640','Sardhana','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('641','Vita','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('642','Gumia','Jharkhand');
INSERT INTO city(id,name,state_name) VALUES ('643','Puttur','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('644','Jalandhar Cantt.','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('645','Nehtaur','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('646','Changanassery','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('647','Mandapeta','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('648','Dumka','Jharkhand');
INSERT INTO city(id,name,state_name) VALUES ('649','Seohara','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('650','Umarkhed','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('651','Madhupur','Jharkhand');
INSERT INTO city(id,name,state_name) VALUES ('652','Vikramasingapuram','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('653','Punalur','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('654','Kendrapara','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('655','Sihor','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('656','Nellikuppam','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('657','Samana','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('658','Warora','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('659','Nilambur','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('660','Rasipuram','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('661','Ramnagar','Uttarakhand');
INSERT INTO city(id,name,state_name) VALUES ('662','Jammalamadugu','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('663','Nawanshahr','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('664','Thoubal','Manipur');
INSERT INTO city(id,name,state_name) VALUES ('665','Athni','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('666','Cherthala','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('667','Sidhi','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('668','Farooqnagar','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('669','Peddapuram','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('670','Chirkunda','Jharkhand');
INSERT INTO city(id,name,state_name) VALUES ('671','Pachora','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('672','Madhepura','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('673','Pithoragarh','Uttarakhand');
INSERT INTO city(id,name,state_name) VALUES ('674','Tumsar','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('675','Phalodi','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('676','Tiruttani','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('677','Rampura Phul','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('678','Perinthalmanna','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('679','Padrauna','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('680','Pipariya','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('681','Dalli-Rajhara','Chhattisgarh');
INSERT INTO city(id,name,state_name) VALUES ('682','Punganur','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('683','Mattannur','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('684','Mathura','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('685','Thakurdwara','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('686','Nandivaram-Guduvancheri','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('687','Mulbagal','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('688','Manjlegaon','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('689','Wankaner','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('690','Sillod','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('691','Nidadavole','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('692','Surapura','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('693','Rajagangapur','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('694','Sheikhpura','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('695','Parlakhemundi','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('696','Kalimpong','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('697','Siruguppa','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('698','Arvi','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('699','Limbdi','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('700','Barpeta','Assam');
INSERT INTO city(id,name,state_name) VALUES ('701','Manglaur','Uttarakhand');
INSERT INTO city(id,name,state_name) VALUES ('702','Repalle','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('703','Mudhol','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('704','Shujalpur','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('705','Mandvi','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('706','Thangadh','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('707','Sironj','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('708','Nandura','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('709','Shoranur','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('710','Nathdwara','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('711','Periyakulam','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('712','Sultanganj','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('713','Medak','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('714','Narayanpet','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('715','Raxaul Bazar','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('716','Rajauri','Jammu and Kashmir');
INSERT INTO city(id,name,state_name) VALUES ('717','Pernampattu','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('718','Nainital','Uttarakhand');
INSERT INTO city(id,name,state_name) VALUES ('719','Ramachandrapuram','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('720','Vaijapur','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('721','Nangal','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('722','Sidlaghatta','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('723','Punch','Jammu and Kashmir');
INSERT INTO city(id,name,state_name) VALUES ('724','Pandhurna','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('725','Wadgaon Road','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('726','Talcher','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('727','Varkala','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('728','Pilani','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('729','Nowgong','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('730','Naila Janjgir','Chhattisgarh');
INSERT INTO city(id,name,state_name) VALUES ('731','Mapusa','Goa');
INSERT INTO city(id,name,state_name) VALUES ('732','Vellakoil','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('733','Merta City','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('734','Sivaganga','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('735','Mandideep','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('736','Sailu','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('737','Vyara','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('738','Kovvur','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('739','Vadalur','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('740','Nawabganj','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('741','Padra','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('742','Sainthia','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('743','Siana','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('744','Shahpur','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('745','Sojat','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('746','Noorpur','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('747','Paravoor','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('748','Murtijapur','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('749','Ramnagar','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('750','Sundargarh','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('751','Taki','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('752','Saundatti-Yellamma','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('753','Pathanamthitta','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('754','Wadi','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('755','Rameshwaram','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('756','Tasgaon','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('757','Sikandra Rao','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('758','Sihora','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('759','Tiruvethipuram','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('760','Tiruvuru','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('761','Mehkar','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('762','Peringathur','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('763','Perambalur','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('764','Manvi','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('765','Zunheboto','Nagaland');
INSERT INTO city(id,name,state_name) VALUES ('766','Mahnar Bazar','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('767','Attingal','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('768','Shahbad','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('769','Puranpur','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('770','Nelamangala','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('771','Nakodar','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('772','Lunawada','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('773','Murshidabad','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('774','Mahe','Puducherry');
INSERT INTO city(id,name,state_name) VALUES ('775','Lanka','Assam');
INSERT INTO city(id,name,state_name) VALUES ('776','Rudauli','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('777','Tuensang','Nagaland');
INSERT INTO city(id,name,state_name) VALUES ('778','Lakshmeshwar','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('779','Zira','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('780','Yawal','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('781','Thana Bhawan','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('782','Ramdurg','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('783','Pulgaon','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('784','Sadasivpet','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('785','Nargund','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('786','Neem-Ka-Thana','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('787','Memari','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('788','Nilanga','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('789','Naharlagun','Arunachal Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('790','Pakaur','Jharkhand');
INSERT INTO city(id,name,state_name) VALUES ('791','Wai','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('792','Tarikere','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('793','Malavalli','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('794','Raisen','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('795','Lahar','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('796','Uravakonda','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('797','Savanur','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('798','Sirohi','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('799','Udhampur','Jammu and Kashmir');
INSERT INTO city(id,name,state_name) VALUES ('800','Umarga','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('801','Pratapgarh','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('802','Lingsugur','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('803','Usilampatti','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('804','Palia Kalan','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('805','Wokha','Nagaland');
INSERT INTO city(id,name,state_name) VALUES ('806','Rajpipla','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('807','Vijayapura','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('808','Rawatbhata','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('809','Sangaria','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('810','Paithan','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('811','Rahuri','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('812','Patti','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('813','Zaidpur','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('814','Lalsot','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('815','Maihar','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('816','Vedaranyam','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('817','Nawapur','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('818','Solan','Himachal Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('819','Vapi','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('820','Sanawad','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('821','Warisaliganj','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('822','Revelganj','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('823','Sabalgarh','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('824','Tuljapur','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('825','Simdega','Jharkhand');
INSERT INTO city(id,name,state_name) VALUES ('826','Musabani','Jharkhand');
INSERT INTO city(id,name,state_name) VALUES ('827','Kodungallur','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('828','Phulabani','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('829','Umreth','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('830','Narsipatnam','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('831','Nautanwa','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('832','Rajgir','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('833','Yellandu','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('834','Sathyamangalam','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('835','Pilibanga','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('836','Morshi','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('837','Pehowa','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('838','Sonepur','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('839','Pappinisseri','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('840','Zamania','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('841','Mihijam','Jharkhand');
INSERT INTO city(id,name,state_name) VALUES ('842','Purna','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('843','Puliyankudi','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('844','Shikarpur, Bulandshahr','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('845','Umaria','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('846','Porsa','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('847','Naugawan Sadat','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('848','Fatehpur Sikri','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('849','Manuguru','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('850','Udaipur','Tripura');
INSERT INTO city(id,name,state_name) VALUES ('851','Pipar City','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('852','Pattamundai','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('853','Nanjikottai','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('854','Taranagar','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('855','Yerraguntla','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('856','Satana','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('857','Sherghati','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('858','Sankeshwara','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('859','Madikeri','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('860','Thuraiyur','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('861','Sanand','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('862','Rajula','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('863','Kyathampalle','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('864','Shahabad, Rampur','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('865','Tilda Newra','Chhattisgarh');
INSERT INTO city(id,name,state_name) VALUES ('866','Narsinghgarh','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('867','Chittur-Thathamangalam','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('868','Malaj Khand','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('869','Sarangpur','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('870','Robertsganj','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('871','Sirkali','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('872','Radhanpur','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('873','Tiruchendur','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('874','Utraula','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('875','Patratu','Jharkhand');
INSERT INTO city(id,name,state_name) VALUES ('876','Vijainagar, Ajmer','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('877','Periyasemur','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('878','Pathri','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('879','Sadabad','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('880','Talikota','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('881','Sinnar','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('882','Mungeli','Chhattisgarh');
INSERT INTO city(id,name,state_name) VALUES ('883','Sedam','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('884','Shikaripur','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('885','Sumerpur','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('886','Sattur','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('887','Sugauli','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('888','Lumding','Assam');
INSERT INTO city(id,name,state_name) VALUES ('889','Vandavasi','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('890','Titlagarh','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('891','Uchgaon','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('892','Mokokchung','Nagaland');
INSERT INTO city(id,name,state_name) VALUES ('893','Paschim Punropara','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('894','Sagwara','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('895','Ramganj Mandi','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('896','Tarakeswar','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('897','Mahalingapura','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('898','Dharmanagar','Tripura');
INSERT INTO city(id,name,state_name) VALUES ('899','Mahemdabad','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('900','Manendragarh','Chhattisgarh');
INSERT INTO city(id,name,state_name) VALUES ('901','Uran','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('902','Tharamangalam','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('903','Tirukkoyilur','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('904','Pen','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('905','Makhdumpur','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('906','Maner','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('907','Oddanchatram','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('908','Palladam','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('909','Mundi','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('910','Nabarangapur','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('911','Mudalagi','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('912','Samalkha','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('913','Nepanagar','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('914','Karjat','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('915','Ranavav','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('916','Pedana','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('917','Pinjore','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('918','Lakheri','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('919','Pasan','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('920','Puttur','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('921','Vadakkuvalliyur','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('922','Tirukalukundram','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('923','Mahidpur','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('924','Mussoorie','Uttarakhand');
INSERT INTO city(id,name,state_name) VALUES ('925','Muvattupuzha','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('926','Rasra','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('927','Udaipurwati','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('928','Manwath','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('929','Adoor','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('930','Uthamapalayam','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('931','Partur','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('932','Nahan','Himachal Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('933','Ladwa','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('934','Mankachar','Assam');
INSERT INTO city(id,name,state_name) VALUES ('935','Nongstoin','Meghalaya');
INSERT INTO city(id,name,state_name) VALUES ('936','Losal','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('937','Sri Madhopur','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('938','Ramngarh','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('939','Mavelikkara','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('940','Rawatsar','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('941','Rajakhera','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('942','Lar','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('943','Lal Gopalganj Nindaura','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('944','Muddebihal','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('945','Sirsaganj','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('946','Shahpura','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('947','Surandai','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('948','Sangole','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('949','Pavagada','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('950','Tharad','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('951','Mansa','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('952','Umbergaon','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('953','Mavoor','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('954','Nalbari','Assam');
INSERT INTO city(id,name,state_name) VALUES ('955','Talaja','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('956','Malur','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('957','Mangrulpir','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('958','Soro','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('959','Shahpura','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('960','Vadnagar','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('961','Raisinghnagar','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('962','Sindhagi','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('963','Sanduru','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('964','Sohna','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('965','Manavadar','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('966','Pihani','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('967','Safidon','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('968','Risod','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('969','Rosera','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('970','Sankari','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('971','Malpura','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('972','Sonamukhi','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('973','Shamsabad, Agra','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('974','Nokha','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('975','PandUrban Agglomeration','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('976','Mainaguri','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('977','Afzalpur','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('978','Shirur','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('979','Salaya','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('980','Shenkottai','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('981','Pratapgarh','Tripura');
INSERT INTO city(id,name,state_name) VALUES ('982','Vadipatti','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('983','Nagarkurnool','Telangana');
INSERT INTO city(id,name,state_name) VALUES ('984','Savner','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('985','Sasvad','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('986','Rudrapur','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('987','Soron','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('988','Sholingur','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('989','Pandharkaoda','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('990','Perumbavoor','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('991','Maddur','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('992','Nadbai','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('993','Talode','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('994','Shrigonda','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('995','Madhugiri','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('996','Tekkalakote','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('997','Seoni-Malwa','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('998','Shirdi','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('999','SUrban Agglomerationr','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1000','Terdal','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('1001','Raver','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('1002','Tirupathur','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1003','Taraori','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('1004','Mukhed','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('1005','Manachanallur','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1006','Rehli','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1007','Sanchore','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('1008','Rajura','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('1009','Piro','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('1010','Mudabidri','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('1011','Vadgaon Kasba','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('1012','Nagar','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('1013','Vijapur','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('1014','Viswanatham','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1015','Polur','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1016','Panagudi','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1017','Manawar','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1018','Tehri','Uttarakhand');
INSERT INTO city(id,name,state_name) VALUES ('1019','Samdhan','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1020','Pardi','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('1021','Rahatgarh','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1022','Panagar','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1023','Uthiramerur','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1024','Tirora','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('1025','Rangia','Assam');
INSERT INTO city(id,name,state_name) VALUES ('1026','Sahjanwa','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1027','Wara Seoni','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1028','Magadi','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('1029','Rajgarh (Alwar)','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('1030','Rafiganj','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('1031','Tarana','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1032','Rampur Maniharan','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1033','Sheoganj','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('1034','Raikot','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('1035','Pauri','Uttarakhand');
INSERT INTO city(id,name,state_name) VALUES ('1036','Sumerpur','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1037','Navalgund','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('1038','Shahganj','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1039','Marhaura','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('1040','Tulsipur','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1041','Sadri','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('1042','Thiruthuraipoondi','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1043','Shiggaon','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('1044','Pallapatti','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1045','Mahendragarh','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('1046','Sausar','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1047','Ponneri','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1048','Mahad','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('1049','Lohardaga','Jharkhand');
INSERT INTO city(id,name,state_name) VALUES ('1050','Tirwaganj','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1051','Margherita','Assam');
INSERT INTO city(id,name,state_name) VALUES ('1052','Sundarnagar','Himachal Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1053','Rajgarh','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1054','Mangaldoi','Assam');
INSERT INTO city(id,name,state_name) VALUES ('1055','Renigunta','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1056','Longowal','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('1057','Ratia','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('1058','Lalgudi','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1059','Shrirangapattana','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('1060','Niwari','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1061','Natham','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1062','Unnamalaikadai','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1063','PurqUrban Agglomerationzi','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1064','Shamsabad, Farrukhabad','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1065','Mirganj','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('1066','Todaraisingh','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('1067','Warhapur','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1068','Rajam','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1069','Urmar Tanda','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('1070','Lonar','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('1071','Powayan','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1072','P.N.Patti','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1073','Palampur','Himachal Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1074','Srisailam Project (Right Flank Colony) Township','Andhra Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1075','Sindagi','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('1076','Sandi','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1077','Vaikom','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('1078','Malda','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('1079','Tharangambadi','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1080','Sakaleshapura','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('1081','Lalganj','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('1082','Malkangiri','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('1083','Rapar','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('1084','Mauganj','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1085','Todabhim','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('1086','Srinivaspur','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('1087','Murliganj','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('1088','Reengus','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('1089','Sawantwadi','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('1090','Tittakudi','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1091','Lilong','Manipur');
INSERT INTO city(id,name,state_name) VALUES ('1092','Rajaldesar','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('1093','Pathardi','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('1094','Achhnera','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1095','Pacode','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1096','Naraura','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1097','Nakur','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1098','Palai','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('1099','Morinda, India','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('1100','Manasa','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1101','Nainpur','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1102','Sahaspur','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1103','Pauni','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('1104','Prithvipur','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1105','Ramtek','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('1106','Silapathar','Assam');
INSERT INTO city(id,name,state_name) VALUES ('1107','Songadh','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('1108','Safipur','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1109','Sohagpur','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1110','Mul','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('1111','Sadulshahar','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('1112','Phillaur','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('1113','Sambhar','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('1114','Prantij','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('1115','Nagla','Uttarakhand');
INSERT INTO city(id,name,state_name) VALUES ('1116','Pattran','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('1117','Mount Abu','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('1118','Reoti','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1119','Tenu dam-cum-Kathhara','Jharkhand');
INSERT INTO city(id,name,state_name) VALUES ('1120','Panchla','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('1121','Sitarganj','Uttarakhand');
INSERT INTO city(id,name,state_name) VALUES ('1122','Pasighat','Arunachal Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1123','Motipur','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('1124','O'' Valley','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1125','Raghunathpur','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('1126','Suriyampalayam','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1127','Qadian','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('1128','Rairangpur','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('1129','Silvassa','Dadra and Nagar Haveli');
INSERT INTO city(id,name,state_name) VALUES ('1130','Nowrozabad (Khodargama)','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1131','Mangrol','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('1132','Soyagaon','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('1133','Sujanpur','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('1134','Manihari','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('1135','Sikanderpur','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1136','Mangalvedhe','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('1137','Phulera','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('1138','Ron','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('1139','Sholavandan','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1140','Saidpur','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1141','Shamgarh','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1142','Thammampatti','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1143','Maharajpur','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1144','Multai','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1145','Mukerian','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('1146','Sirsi','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1147','Purwa','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1148','Sheohar','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('1149','Namagiripettai','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1150','Parasi','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1151','Lathi','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('1152','Lalganj','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1153','Narkhed','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('1154','Mathabhanga','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('1155','Shendurjana','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('1156','Peravurani','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1157','Mariani','Assam');
INSERT INTO city(id,name,state_name) VALUES ('1158','Phulpur','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1159','Rania','Haryana');
INSERT INTO city(id,name,state_name) VALUES ('1160','Pali','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1161','Pachore','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1162','Parangipettai','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1163','Pudupattinam','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1164','Panniyannur','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('1165','Maharajganj','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('1166','Rau','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1167','Monoharpur','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('1168','Mandawa','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('1169','Marigaon','Assam');
INSERT INTO city(id,name,state_name) VALUES ('1170','Pallikonda','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1171','Pindwara','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('1172','Shishgarh','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1173','Patur','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('1174','Mayang Imphal','Manipur');
INSERT INTO city(id,name,state_name) VALUES ('1175','Mhowgaon','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1176','Guruvayoor','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('1177','Mhaswad','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('1178','Sahawar','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1179','Sivagiri','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1180','Mundargi','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('1181','Punjaipugalur','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1182','Kailasahar','Tripura');
INSERT INTO city(id,name,state_name) VALUES ('1183','Samthar','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1184','Sakti','Chhattisgarh');
INSERT INTO city(id,name,state_name) VALUES ('1185','Sadalagi','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('1186','Silao','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('1187','Mandalgarh','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('1188','Loha','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('1189','Pukhrayan','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1190','Padmanabhapuram','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1191','Belonia','Tripura');
INSERT INTO city(id,name,state_name) VALUES ('1192','Saiha','Mizoram');
INSERT INTO city(id,name,state_name) VALUES ('1193','Srirampore','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('1194','Talwara','Punjab');
INSERT INTO city(id,name,state_name) VALUES ('1195','Puthuppally','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('1196','Khowai','Tripura');
INSERT INTO city(id,name,state_name) VALUES ('1197','Vijaypur','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1198','Takhatgarh','Rajasthan');
INSERT INTO city(id,name,state_name) VALUES ('1199','Thirupuvanam','Tamil Nadu');
INSERT INTO city(id,name,state_name) VALUES ('1200','Adra','West Bengal');
INSERT INTO city(id,name,state_name) VALUES ('1201','Piriyapatna','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('1202','Obra','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1203','Adalaj','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('1204','Nandgaon','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('1205','Barh','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('1206','Chhapra','Gujarat');
INSERT INTO city(id,name,state_name) VALUES ('1207','Panamattom','Kerala');
INSERT INTO city(id,name,state_name) VALUES ('1208','Niwai','Uttar Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1209','Bageshwar','Uttarakhand');
INSERT INTO city(id,name,state_name) VALUES ('1210','Tarbha','Odisha');
INSERT INTO city(id,name,state_name) VALUES ('1211','Adyar','Karnataka');
INSERT INTO city(id,name,state_name) VALUES ('1212','Narsinghgarh','Madhya Pradesh');
INSERT INTO city(id,name,state_name) VALUES ('1213','Warud','Maharashtra');
INSERT INTO city(id,name,state_name) VALUES ('1214','Asarganj','Bihar');
INSERT INTO city(id,name,state_name) VALUES ('1215','Sarsod','Haryana');