INSERT INTO country(id,name) VALUES (1,'Afghanistan');
INSERT INTO country(id,name) VALUES (2,'Albania');
INSERT INTO country(id,name) VALUES (3,'Algeria');
INSERT INTO country(id,name) VALUES (4,'American Samoa');
INSERT INTO country(id,name) VALUES (5,'Andorra');
INSERT INTO country(id,name) VALUES (6,'Angola');
INSERT INTO country(id,name) VALUES (7,'Anguilla');
INSERT INTO country(id,name) VALUES (8,'Antarctica');
INSERT INTO country(id,name) VALUES (9,'Antigua and Barbuda');
INSERT INTO country(id,name) VALUES (10,'Argentina');
INSERT INTO country(id,name) VALUES (11,'Armenia');
INSERT INTO country(id,name) VALUES (12,'Aruba');
INSERT INTO country(id,name) VALUES (13,'Australia');
INSERT INTO country(id,name) VALUES (14,'Austria');
INSERT INTO country(id,name) VALUES (15,'Azerbaijan');
INSERT INTO country(id,name) VALUES (16,'Bahamas');
INSERT INTO country(id,name) VALUES (17,'Bahrain');
INSERT INTO country(id,name) VALUES (18,'Bangladesh');
INSERT INTO country(id,name) VALUES (19,'Barbados');
INSERT INTO country(id,name) VALUES (20,'Belarus');
INSERT INTO country(id,name) VALUES (21,'Belgium');
INSERT INTO country(id,name) VALUES (22,'Belize');
INSERT INTO country(id,name) VALUES (23,'Benin');
INSERT INTO country(id,name) VALUES (24,'Bermuda');
INSERT INTO country(id,name) VALUES (25,'Bhutan');
INSERT INTO country(id,name) VALUES (26,'Bolivia');
INSERT INTO country(id,name) VALUES (27,'Bonaire');
INSERT INTO country(id,name) VALUES (28,'Bosnia and Herzegovina');
INSERT INTO country(id,name) VALUES (29,'Botswana');
INSERT INTO country(id,name) VALUES (30,'Bouvet Island');
INSERT INTO country(id,name) VALUES (31,'Brazil');
INSERT INTO country(id,name) VALUES (32,'British Indian Ocean Territory');
INSERT INTO country(id,name) VALUES (33,'Brunei Darussalam');
INSERT INTO country(id,name) VALUES (34,'Bulgaria');
INSERT INTO country(id,name) VALUES (35,'Burkina Faso');
INSERT INTO country(id,name) VALUES (36,'Burundi');
INSERT INTO country(id,name) VALUES (37,'Cabo Verde');
INSERT INTO country(id,name) VALUES (38,'Cambodia');	
INSERT INTO country(id,name) VALUES (39,'Cameroon');
INSERT INTO country(id,name) VALUES (40,'Canada');
INSERT INTO country(id,name) VALUES (41,'Cayman Islands');
INSERT INTO country(id,name) VALUES (42,'Central African Republic');
INSERT INTO country(id,name) VALUES (43,'Chad');
INSERT INTO country(id,name) VALUES (44,'Chile');
INSERT INTO country(id,name) VALUES (45,'China');
INSERT INTO country(id,name) VALUES (46,'Christmas Island');
INSERT INTO country(id,name) VALUES (47,'Cocos (Keeling) Islands');
INSERT INTO country(id,name) VALUES (48,'Colombia');
INSERT INTO country(id,name) VALUES (49,'Comoros');
INSERT INTO country(id,name) VALUES (50,'Congo');
INSERT INTO country(id,name) VALUES (51,'Congo, Democratic Republic of the');
INSERT INTO country(id,name) VALUES (52,'Cook Islands');
INSERT INTO country(id,name) VALUES (53,'Costa Rica');
INSERT INTO country(id,name) VALUES (54,'Croatia');
INSERT INTO country(id,name) VALUES (55,'Cuba');
INSERT INTO country(id,name) VALUES (56,'Cyprus');
INSERT INTO country(id,name) VALUES (57,'Czechia');
INSERT INTO country(id,name) VALUES (58,'Denmark');
INSERT INTO country(id,name) VALUES (59,'Djibouti');
INSERT INTO country(id,name) VALUES (60,'Dominica');
INSERT INTO country(id,name) VALUES (61,'Dominican Republic');
INSERT INTO country(id,name) VALUES (62,'Ecuador');
INSERT INTO country(id,name) VALUES (63,'Egypt');
INSERT INTO country(id,name) VALUES (64,'El Salvador');
INSERT INTO country(id,name) VALUES (65,'Equatorial Guinea');
INSERT INTO country(id,name) VALUES (66,'Eritrea');
INSERT INTO country(id,name) VALUES (67,'Estonia');
INSERT INTO country(id,name) VALUES (68,'Eswatini');
INSERT INTO country(id,name) VALUES (69,'Ethiopia');
INSERT INTO country(id,name) VALUES (70,'Falkland Islands (Malvinas)');
INSERT INTO country(id,name) VALUES (71,'Faroe Islands');
INSERT INTO country(id,name) VALUES (72,'Fiji');
INSERT INTO country(id,name) VALUES (73,'Finland');
INSERT INTO country(id,name) VALUES (74,'France');
INSERT INTO country(id,name) VALUES (75,'French Guiana');
INSERT INTO country(id,name) VALUES (76,'French Polynesia');
INSERT INTO country(id,name) VALUES (77,'French Southern Territories');
INSERT INTO country(id,name) VALUES (78,'Gabon');
INSERT INTO country(id,name) VALUES (79,'Gambia');
INSERT INTO country(id,name) VALUES (80,'Georgia');
INSERT INTO country(id,name) VALUES (81,'Germany');
INSERT INTO country(id,name) VALUES (82,'Ghana');
INSERT INTO country(id,name) VALUES (83,'Gibraltar');
INSERT INTO country(id,name) VALUES (84,'Greece');
INSERT INTO country(id,name) VALUES (85,'Greenland');
INSERT INTO country(id,name) VALUES (86,'Grenada');
INSERT INTO country(id,name) VALUES (87,'Guadeloupe');
INSERT INTO country(id,name) VALUES (88,'Guam');
INSERT INTO country(id,name) VALUES (89,'Guatemala');
INSERT INTO country(id,name) VALUES (90,'Guernsey');
INSERT INTO country(id,name) VALUES (91,'Guinea');
INSERT INTO country(id,name) VALUES (92,'Guinea-Bissau');
INSERT INTO country(id,name) VALUES (93,'Guyana');
INSERT INTO country(id,name) VALUES (94,'Haiti');
INSERT INTO country(id,name) VALUES (95,'Heard Island and McDonald Islands');
INSERT INTO country(id,name) VALUES (96,'Holy See');
INSERT INTO country(id,name) VALUES (97,'Honduras');
INSERT INTO country(id,name) VALUES (98,'Hong Kong');
INSERT INTO country(id,name) VALUES (99,'Hungary');
INSERT INTO country(id,name) VALUES (100,'Iceland');
INSERT INTO country(id,name) VALUES (101,'India');
INSERT INTO country(id,name) VALUES (102,'Indonesia');
INSERT INTO country(id,name) VALUES (103,'Iran (Islamic Republic of)');
INSERT INTO country(id,name) VALUES (104,'Iraq');
INSERT INTO country(id,name) VALUES (105,'Ireland');
INSERT INTO country(id,name) VALUES (106,'Isle of Man');
INSERT INTO country(id,name) VALUES (107,'Israel');
INSERT INTO country(id,name) VALUES (108,'Italy');
INSERT INTO country(id,name) VALUES (109,'Jamaica');
INSERT INTO country(id,name) VALUES (110,'Japan');
INSERT INTO country(id,name) VALUES (111,'Jersey');
INSERT INTO country(id,name) VALUES (112,'Jordan');
INSERT INTO country(id,name) VALUES (113,'Kazakhstan');
INSERT INTO country(id,name) VALUES (114,'Kenya');
INSERT INTO country(id,name) VALUES (115,'Kiribati');
INSERT INTO country(id,name) VALUES (116,'Korea');
INSERT INTO country(id,name) VALUES (117,'Kuwait');
INSERT INTO country(id,name) VALUES (118,'Kyrgyzstan');
INSERT INTO country(id,name) VALUES (119,'Lao');
INSERT INTO country(id,name) VALUES (120,'Latvia');
INSERT INTO country(id,name) VALUES (121,'Lebanon');
INSERT INTO country(id,name) VALUES (122,'Lesotho');
INSERT INTO country(id,name) VALUES (123,'Liberia');
INSERT INTO country(id,name) VALUES (124,'Libya');
INSERT INTO country(id,name) VALUES (125,'Liechtenstein');
INSERT INTO country(id,name) VALUES (126,'Lithuania');
INSERT INTO country(id,name) VALUES (127,'Luxembourg');
INSERT INTO country(id,name) VALUES (128,'Macao');
INSERT INTO country(id,name) VALUES (129,'Madagascar');
INSERT INTO country(id,name) VALUES (130,'Malawi');
INSERT INTO country(id,name) VALUES (131,'Malaysia');
INSERT INTO country(id,name) VALUES (132,'Maldives');
INSERT INTO country(id,name) VALUES (133,'Mali');
INSERT INTO country(id,name) VALUES (134,'Malta');
INSERT INTO country(id,name) VALUES (135,'Marshall Islands');
INSERT INTO country(id,name) VALUES (136,'Martinique');
INSERT INTO country(id,name) VALUES (137,'Mauritania');
INSERT INTO country(id,name) VALUES (138,'Mauritius');
INSERT INTO country(id,name) VALUES (139,'Mayotte');
INSERT INTO country(id,name) VALUES (140,'Mexico');
INSERT INTO country(id,name) VALUES (141,'Micronesia');
INSERT INTO country(id,name) VALUES (142,'Monaco');
INSERT INTO country(id,name) VALUES (143,'Mongolia');
INSERT INTO country(id,name) VALUES (144,'Montenegro');
INSERT INTO country(id,name) VALUES (145,'Montserrat');
INSERT INTO country(id,name) VALUES (146,'Morocco');
INSERT INTO country(id,name) VALUES (147,'Mozambique');
INSERT INTO country(id,name) VALUES (148,'Myanmar');
INSERT INTO country(id,name) VALUES (149,'Namibia');
INSERT INTO country(id,name) VALUES (150,'Nauru');
INSERT INTO country(id,name) VALUES (151,'Nepal');
INSERT INTO country(id,name) VALUES (152,'Netherlands');
INSERT INTO country(id,name) VALUES (153,'New Caledonia');
INSERT INTO country(id,name) VALUES (154,'New Zealand');
INSERT INTO country(id,name) VALUES (155,'Nicaragua');
INSERT INTO country(id,name) VALUES (156,'Niger');
INSERT INTO country(id,name) VALUES (157,'Nigeria');
INSERT INTO country(id,name) VALUES (158,'Niue');
INSERT INTO country(id,name) VALUES (159,'Norfolk Island');
INSERT INTO country(id,name) VALUES (160,'North Macedonia');
INSERT INTO country(id,name) VALUES (161,'Northern Mariana Islands');
INSERT INTO country(id,name) VALUES (162,'Norway');
INSERT INTO country(id,name) VALUES (163,'Oman');
INSERT INTO country(id,name) VALUES (164,'Pakistan');
INSERT INTO country(id,name) VALUES (165,'Palau');
INSERT INTO country(id,name) VALUES (166,'Palestine, State of');
INSERT INTO country(id,name) VALUES (167,'Panama');
INSERT INTO country(id,name) VALUES (168,'Papua New Guinea');
INSERT INTO country(id,name) VALUES (169,'Paraguay');
INSERT INTO country(id,name) VALUES (170,'Peru');
INSERT INTO country(id,name) VALUES (171,'Philippines');
INSERT INTO country(id,name) VALUES (172,'Pitcairn');
INSERT INTO country(id,name) VALUES (173,'Poland');
INSERT INTO country(id,name) VALUES (174,'Portugal');
INSERT INTO country(id,name) VALUES (175,'Puerto Rico');
INSERT INTO country(id,name) VALUES (176,'Qatar');
INSERT INTO country(id,name) VALUES (177,'Romania');
INSERT INTO country(id,name) VALUES (178,'Russian Federation');
INSERT INTO country(id,name) VALUES (179,'Rwanda');
INSERT INTO country(id,name) VALUES (180,'Samoa');
INSERT INTO country(id,name) VALUES (181,'San Marino');
INSERT INTO country(id,name) VALUES (182,'Sao Tome and Principe');
INSERT INTO country(id,name) VALUES (183,'Saudi Arabia');
INSERT INTO country(id,name) VALUES (184,'Senegal');
INSERT INTO country(id,name) VALUES (185,'Serbia');
INSERT INTO country(id,name) VALUES (186,'Seychelles');
INSERT INTO country(id,name) VALUES (187,'Sierra Leone');
INSERT INTO country(id,name) VALUES (188,'Singapore');
INSERT INTO country(id,name) VALUES (189,'Slovakia');
INSERT INTO country(id,name) VALUES (190,'Slovenia');
INSERT INTO country(id,name) VALUES (191,'Solomon Islands');
INSERT INTO country(id,name) VALUES (192,'Somalia');
INSERT INTO country(id,name) VALUES (193,'South Africa');
INSERT INTO country(id,name) VALUES (194,'South Sudan');
INSERT INTO country(id,name) VALUES (195,'Spain');
INSERT INTO country(id,name) VALUES (196,'Sri Lanka');
INSERT INTO country(id,name) VALUES (197,'Sudan');
INSERT INTO country(id,name) VALUES (198,'Suriname');
INSERT INTO country(id,name) VALUES (199,'Sweden');
INSERT INTO country(id,name) VALUES (200,'Switzerland');
INSERT INTO country(id,name) VALUES (201,'Syrian Arab Republic');
INSERT INTO country(id,name) VALUES (202,'Taiwan');
INSERT INTO country(id,name) VALUES (203,'Tajikistan');
INSERT INTO country(id,name) VALUES (204,'Tanzania');
INSERT INTO country(id,name) VALUES (205,'Thailand');
INSERT INTO country(id,name) VALUES (206,'Timor-Leste');
INSERT INTO country(id,name) VALUES (207,'Togo');
INSERT INTO country(id,name) VALUES (208,'Tokelau');
INSERT INTO country(id,name) VALUES (209,'Tonga');
INSERT INTO country(id,name) VALUES (210,'Trinidad and Tobago');
INSERT INTO country(id,name) VALUES (211,'Tunisia');
INSERT INTO country(id,name) VALUES (212,'Turkey');
INSERT INTO country(id,name) VALUES (213,'Turkmenistan');
INSERT INTO country(id,name) VALUES (214,'Tuvalu');
INSERT INTO country(id,name) VALUES (215,'Uganda');
INSERT INTO country(id,name) VALUES (216,'Ukraine');
INSERT INTO country(id,name) VALUES (217,'UAE');
INSERT INTO country(id,name) VALUES (218,'UK');
INSERT INTO country(id,name) VALUES (219,'USA');
INSERT INTO country(id,name) VALUES (220,'Uruguay');
INSERT INTO country(id,name) VALUES (221,'Uzbekistan');
INSERT INTO country(id,name) VALUES (222,'Vanuatu');
INSERT INTO country(id,name) VALUES (223,'Venezuela');
INSERT INTO country(id,name) VALUES (224,'Viet Nam');
INSERT INTO country(id,name) VALUES (225,'Virgin Islands (British)');
INSERT INTO country(id,name) VALUES (226,'Virgin Islands (U.S.)');
INSERT INTO country(id,name) VALUES (227,'Wallis and Futuna');
INSERT INTO country(id,name) VALUES (228,'Western Sahara');
INSERT INTO country(id,name) VALUES (229,'Yemen');
INSERT INTO country(id,name) VALUES (230,'Zambia');
INSERT INTO country(id,name) VALUES (231,'Zimbabwe');
