INSERT INTO state(id,name,country_name) VALUES (1,'Andhra Pradesh','India');
INSERT INTO state(id,name,country_name) VALUES (2,'Arunachal Pradesh','India');
INSERT INTO state(id,name,country_name) VALUES (3,'Assam','India');
INSERT INTO state(id,name,country_name) VALUES (4,'Bihar','India');
INSERT INTO state(id,name,country_name) VALUES (5,'Chhattisgarh','India');
INSERT INTO state(id,name,country_name) VALUES (6,'Goa','India');
INSERT INTO state(id,name,country_name) VALUES (7,'Gujarat','India');
INSERT INTO state(id,name,country_name) VALUES (8,'Haryana','India');
INSERT INTO state(id,name,country_name) VALUES (9,'Himachal Pradesh','India');
INSERT INTO state(id,name,country_name) VALUES (10,'Jammu and Kashmir','India');
INSERT INTO state(id,name,country_name) VALUES (11,'Jharkhand','India');
INSERT INTO state(id,name,country_name) VALUES (12,'Karnataka','India');
INSERT INTO state(id,name,country_name) VALUES (13,'Kerala','India');
INSERT INTO state(id,name,country_name) VALUES (14,'Madhya Pradesh','India');
INSERT INTO state(id,name,country_name) VALUES (15,'Maharashtra','India');
INSERT INTO state(id,name,country_name) VALUES (16,'Manipur','India');
INSERT INTO state(id,name,country_name) VALUES (17,'Meghalaya','India');
INSERT INTO state(id,name,country_name) VALUES (18,'Mizoram','India');
INSERT INTO state(id,name,country_name) VALUES (19,'Nagaland','India');
INSERT INTO state(id,name,country_name) VALUES (20,'Odisha','India');
INSERT INTO state(id,name,country_name) VALUES (21,'Punjab','India');
INSERT INTO state(id,name,country_name) VALUES (22,'Rajasthan','India');
INSERT INTO state(id,name,country_name) VALUES (23,'Sikkim','India');
INSERT INTO state(id,name,country_name) VALUES (24,'Tamil Nadu','India');
INSERT INTO state(id,name,country_name) VALUES (25,'Telangana','India');
INSERT INTO state(id,name,country_name) VALUES (26,'Tripura','India');
INSERT INTO state(id,name,country_name) VALUES (27,'Uttar Pradesh','India');
INSERT INTO state(id,name,country_name) VALUES (28,'Uttarakhand','India');
INSERT INTO state(id,name,country_name) VALUES (29,'West Bengal','India');
INSERT INTO state(id,name,country_name) VALUES (30,'Delhi','India');
